name: Release
on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    if: "startsWith(github.event.head_commit.message, 'release:')"
    name: Build and publish package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: python -m pip install -U setuptools wheel build

      - name: Build
        run: python -m build .

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
